# Start with an empty image (scratch)
FROM scratch

# Copy the statically compiled Go binary into the container
COPY hello-world /hello-world

# Set the entry point to execute the Go binary
ENTRYPOINT ["/hello-world"]

